AllCops:
  Include:
    - 'Rakefile'
    - 'config.ru'
    - '*.gemspec'
    - 'Gemfile'

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

FileName:
  Exclude:
    - 'lib/magnet-markdown.rb'
  Enabled: true

LineLength:
  Max: 124
